name: Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  packer-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        id: setup


      - name: Initialize Packer (Install plugins)
        run: packer init ./Packer/.

      - name: Check Packer Format
        run: formatted=$(packer fmt -check ./Packer/.)



      - name: Validate Packer Template
        run: packer validate ./Packer/.
