name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest


    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{secrets.DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{secrets.DB}}
          POSTGRES_HOST: ${{secrets.DB_HOST}}
          POSTGRES_PORT: ${{secrets.PORT}}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test
        env:
          LOCALHOST: ${{secrets.DB_HOST}}
          PORT: ${{secrets.PORT}}
          DB: ${{secrets.DB}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: mvn clean install -B

      - name: to see name
        run : ls -l ./opt/

      - name : Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
          aws-secret-access-key : ${{secrets.AWS_ACCESS_KEY}}
          aws-region : ${{secrets.AWS_REGION}}

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Initialize Packer (Install plugins)
        run: packer init ./Packer/.

      - name: Check Packer Format
        run: packer fmt ./Packer/.

      - name: Validate Packer Template
        run: packer validate ./Packer/.

      - name: packer building
        run: packer build -var "source_jar=target/CloudAssignment2-0.0.1-SNAPSHOT.jar" -var "source_ami=${{secrets.AMI_ID}}" ./Packer/.



