name: Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  packer-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@v1.1.3
        with:
          version: '1.9.4'


      - name: Check Packer Format
        run: packer fmt src/main/java/com/csye6225/CloudAssignment2/Packer/custom-ami.pkr.hcl

      - name: Validate Packer Template
        run: packer validate src/main/java/com/csye6225/CloudAssignment2/Packer/custom-ami.pkr.hcl

