name: Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  packer-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Packer
        uses: hashicorp/setup-packer@main
        id: setup


      - name: Initialize Packer (Install plugins)
        run: packer init src/main/java/com/csye6225/CloudAssignment2/Packer/custom-ami.pkr.hcl

      - name: Check Packer Format
        run: |
          formatted=$(packer fmt -check src/main/java/com/csye6225/CloudAssignment2/Packer/custom-ami.pkr.hcl)
          if [[ $formatted != "" ]]; then
            echo "Packer template is not formatted correctly. Please run 'packer fmt'."
            exit 1
          fi

      - name: Validate Packer Template
        run: packer validate src/main/java/com/csye6225/CloudAssignment2/Packer/custom-ami.pkr.hcl
